# Generated by Django 3.0 on 2021-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
